<a href="https://colab.research.google.com/github/llRodroll/CinD_23-II/blob/main/03_DS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **1. What is a data structre?**

Something that let me store several values.

# **2. Linear Algebra - Numpy**

Numpy = Numerical Python

In [1]:
# Libraries
import numpy as np

## 2.1. Numpy arrays - Vectors and Matrices

In [2]:
# Column Vector
x = np.array([[1],[2],[3]])
print(x)
print(x.shape)

[[1]
 [2]
 [3]]
(3, 1)


In [4]:
# Row Vector
y = np.array([[3, 4, 5]])
print(y)
print(y.shape)

[[3 4 5]]
(1, 3)


In [5]:
# Matrix
M = np.array([[1, 2, 3],
              [4, 5 ,6],
              [7, 8, 9]])
print(M)
print(M.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [6]:
# A nice trick
n, m = M.shape
print('number of rows in M:', n)
print('number of columns in M:', m)

number of rows in M: 3
number of columns in M: 3
