<a href="https://colab.research.google.com/github/llRodroll/CinD_23-II/blob/main/03_DS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **1. What is a data structre?**

Something that let me store several values.

# **2. Linear Algebra - Numpy**

Numpy = Numerical Python

In [2]:
# Libraries
import numpy as np

## 2.1. Numpy arrays - Vectors and Matrices

In [3]:
# Column Vector
x = np.array([[1],[2],[3]])
print(x)
print(x.shape)

[[1]
 [2]
 [3]]
(3, 1)


In [4]:
# Row Vector
y = np.array([[3, 4, 5]])
print(y)
print(y.shape)

[[3 4 5]]
(1, 3)


In [5]:
# Matrix
M = np.array([[1, 2, 3],
              [4, 5 ,6],
              [7, 8, 9]])
print(M)
print(M.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [6]:
# A nice trick
n, m = M.shape
print('number of rows in M:', n)
print('number of columns in M:', m)

number of rows in M: 3
number of columns in M: 3


## 2.2. Slicing with matrices

In [7]:
# Access 1 element

## For vector
### Column Vector
print(x[2,0])
### Row Vector
print(y[0,0])

## For matrix
print(M[1,1])

3
3
5


In [ ]:
# Exercise - Practice
## Using a for loop display/print the number of the row,
## the number of the column, and the element for
## every element in the Matrix M

for j in range(0,3):
  for i in range(0,3):
    print("Row Position:", j+1, "Column Position", i+1, "Element:", M[j,i])

## 2.3. Extract subsets

In [23]:
# Extract an entire Row
print(M[1,])

# Extract an entire Column
print(M[:,1])

[4 5 6]
[2 5 8]


In [25]:
# Extract the elements of the
# last row and columns 2 and 3
print(M[2,1:3])

[8 9]


In [26]:
# Extract the elements of the
# first two rows and the last two columns
print(M[0:2,1:3])

[[2 3]
 [5 6]]


## 2.4. Useful methods

In [32]:
# Zeros

## One dimensiom
z1 = np.zeros(7)
print("z1")
print(z1)

## Two dimensions
z2 = np.zeros((3,5))
print("z2")
print(z2)

z1
[0. 0. 0. 0. 0. 0. 0.]
z2
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
# Ones

## One dimensiom
o1 = np.ones(7)
print("o1")
print(o1)

## Two dimensions
o2 = np.ones((3,5))
print("o2")
print(o2)

In [ ]:
# Full

## One dimesion
f1 = np.full(3,13)
print("f1")
print(f1)

## Two dimesions
f2 = np.full((3,2),17)
print("f2")
print(f2)

In [ ]:
# Sequence

## Simple
s1 = np.arange(10)
print("s1")
print(s1)

## Not that simple
s2 = np.arange(start = 2, stop = 15)
print("s2")
print(s2)

## Custom
s3 = np.arange(start = 2, stop = 15, step = 3)
print("s3")
print(s3)

In [ ]:
# Linear Space

l1 = np.linspace(0,2,5)
print("l1")
print(l1)

## 2.5. Random numbers

In [67]:
# Uniform distribution - [0, 1)
# np.random.seed(1234) - fix the similation
np.random.rand()

0.7853585837137692

In [87]:
# Example - Toss coin simulation

if np.random.rand() <= 0.5:
  print("Heads")
else:
  print("Tails")

Heads
